In [1]:
import csv
import math
import re
import numpy as np
import emoji
import emot
import random



x_train = open('X_train.txt').readlines()
y_train = open('Y_train.txt').readlines()
x_test = open('X_test.txt').readlines()

y_train = [ 0 if x == "0\n" else 1 for x in y_train]  
y_train = np.matrix([y_train])#np.transpose(np.matrix([y_train]))
        # self.distribution_aggresive = {}
        # self.distributive_not_aggresive = {}
final = []
count_in_doc = {}
l = []
word_dict = {}
        # self.document_count()

def tokenize( s):
    #Lowercase every string
    s = s.lower()
    #convert emojis to text
    s = emoji.demojize(s, delimiters=("", ""))
    s = emoji.demojize(s, delimiters=("", ""))
    answ = emot.emoticons(s)
    if(str(type(answ))== "<class 'list'>"):
        answ = answ[0]
    if(answ['flag']):
        # s = s.replace(answ['value'],answ['mean'])
        j = 0
        for i in answ['value']:
            s = s.replace(i, " "+ answ['mean'][j].split()[-1])
            j = j+1
    # s = s.replace(ans['value'],ans['mean'])
    # Remove punctuation and all weird characters
    s = re.sub("\W"," ", s)
    # Special character cleaning
    s = re.sub("\s"," ", s)
    return list(s.split())

def document_count():
    for x in x_train:
        for i in tokenize(x):
            if i not in count_in_doc:
                word_dict[i] = []
                count_in_doc[i] = [0]*12000
    count_in_doc["BIAS"]= [1]*12000
    for k in range(len(x_train)):
        i_long = tokenize(x_train[k])
        for i in i_long:
            count_in_doc[i][k] = (i_long.count(i))
    l = []
    for key, value in count_in_doc.items():
        l.append(count_in_doc[key])
    l = np.transpose(np.matrix(l))
    print(l.shape)
    final = l 
    return final
    




def sigmoid(x):
    return 1/(1+np.exp(-1*x))

def log_likelihood( b):
    pass

def zero_or_one(x):
    if(x>(0.50)):
        return 1 
    return 0
sigmoid_vec = np.vectorize(sigmoid)

final = document_count()
# print(len(x_train))

(12000, 13331)


In [19]:

y_train =np.transpose(y_train)
print(y_train)

zero_or_one_vec =   np.vectorize(zero_or_one)

[[0]
 [1]
 [0]
 ...
 [1]
 [0]
 [0]]


In [141]:
def middle_layer_1__inital_matrix(): 
    number_of_neurons = 10
    layer1_weights =  np.zeros( final.shape[1]) #np.random.normal(size = final.shape[1])  #number_of_neurons) 
    return layer1_weights


layer1_weights = middle_layer_1__inital_matrix()
layer1_weights = np.transpose(np.matrix(layer1_weights))
print(np.sum(layer1_weights))
layer1_weights.shape

0.0


(13331, 1)

In [142]:
def gradient_cal():
    y_result = y_train - zero_or_one_vec(sigmoid_vec(final *layer1_weights  ))
    return np.transpose(final)*y_result

In [143]:
def gradient_cal(n):
    y_result = y_train[n] - zero_or_one_vec(sigmoid_vec(final[n] *layer1_weights  ))
    return np.transpose(final[n])*y_result

In [144]:
y_train[2]- zero_or_one_vec(sigmoid_vec(final[2] *layer1_weights  ))

matrix([[0]])

In [46]:
np.count_nonzero(gradient_cal(112) == gradient_cal(121) )

13308

In [176]:
gradient_cal(4)

matrix([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]])

In [27]:
gradient_cal(4).shape

(13331, 1)

In [127]:
def log_likelihood():
    return np.sum(np.multiply(y_train , (final * layer1_weights))) - np.sum(np.log(1+ np.exp((final *layer1_weights ))))

In [128]:
log_likelihood()



-8317.766166719342

In [40]:
random_number = random.randint(0,final.shape[0])
random_number

970

In [145]:
n =gradient_cal(random_number)
layer1_weights = layer1_weights + learning_rate* n
print(log_likelihood())

-8317.95353166903


In [168]:
learning_rate = 5*(10**(-4))
learning_rate

0.0005

In [169]:
for i in range(100000):
    random_number = random.randint(0,final.shape[0]-1)
    n =gradient_cal(random_number)
    layer1_weights = layer1_weights + learning_rate* n
    if(i%1000 == 0):
        print(log_likelihood())

-8314.789825531236
-8308.401705741153
-8306.420425707083
-8308.923304280604
-8302.030474482779
-8305.599901788308
-8303.915354838176
-8303.24248688533
-8302.957992550548
-8305.282667291345
-8301.147692376588
-8302.021158082796
-8299.996508238324
-8297.821593859006
-8298.009014248202
-8297.185983163747
-8296.269735691003
-8297.50198445491
-8297.26871132068
-8297.80517188327
-8296.045732114577
-8296.769409510216
-8292.078882312468
-8296.550458364509
-8296.113477998395
-8296.531714781358
-8294.050610387672
-8298.433492023678
-8293.654710708915
-8296.766347608956
-8295.796317462738
-8292.450202772574
-8291.574675332267
-8296.331034406563
-8295.641063168128
-8292.989209953925
-8294.812819462455
-8294.186710619313
-8291.199052602935
-8292.949214390883
-8290.490119342974
-8291.870700094847
-8292.719314313736
-8294.787620918703
-8292.389405205058
-8290.85082162559
-8294.09590035349
-8292.801738241566
-8294.355661506344
-8291.039389975937
-8294.10561970644
-8292.28439061832
-8291.645233380237
-

In [147]:
print(log_likelihood())

-8314.789825531236


In [148]:
layer1_weights

matrix([[ 1.0e-04],
        [-2.0e-04],
        [-3.0e-04],
        ...,
        [-5.0e-05],
        [-5.0e-05],
        [-2.5e-04]])

In [160]:
layer1_weights[6]

matrix([[5.e-05]])

In [161]:
temp_count_in_doc = {}
size = len(x_test)
for key, value in count_in_doc.items():
    temp_count_in_doc[key] = [0]* size

for k in range(len(x_test)):
    i_long = tokenize(x_test[k])
    for i in i_long:
        if(i in temp_count_in_doc):
            temp_count_in_doc[i][k] = (i_long.count(i))
            

l = []
for key, value in temp_count_in_doc.items():
    l.append(temp_count_in_doc[key])
l = np.transpose(np.matrix(l))

In [162]:
l.shape

(8001, 13331)

In [163]:
result1= zero_or_one_vec(sigmoid_vec(l *layer1_weights  ))

In [164]:
result = np.transpose(result1).tolist()[0]

In [165]:
result

[0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,


In [166]:
f = open('numbers_lr.csv', 'w')
with f:
    writer = csv.writer(f)
    writer.writerow(["Id", "Category"])
    n= 0 
    for row in result:
        writer.writerow([n ,row])
        n = n+1

In [167]:
layer1_weights

matrix([[ 1.0e-04],
        [-2.0e-04],
        [-3.0e-04],
        ...,
        [-5.0e-05],
        [-5.0e-05],
        [-2.5e-04]])

In [175]:
for i in range(0, 500, 75):
    print(i/250)

0.0
0.3
0.6
0.9
1.2
1.5
1.8


In [196]:
import csv
import math
import re
import numpy as np
import emoji
import emot
import random
from matplotlib import pyplot as plt
from sklearn.metrics import f1_score


class LR_v1:

    # Change this value to change the learning rate
    learning_rate = 5*(10**(-5))
    # Steps to do stocastic Gradient descent by 
    steps = 100000

    '''
    This funtion intializes and sets the global variables for the whole class
    '''
    def __init__(self, x_train, x_test, y_train):
        self.x_train = x_train
        self.y_train = np.matrix([y_train ])
        self.y_train = np.transpose(self.y_train)
        
        self.x_test = x_test
        self.X_dict = {}
        self.X = self.document_count()
        self.weights = self.weights()
        self.training_data_log_likehood = []
        # print(self.X.shape, self.)

    # This makes a weights matrix to calculate train the matrix
    def weights(self): 
        number_of_connections = self.X.shape[1]
        weights =  np.zeros( number_of_connections)
        # Un comment this for random non zero values on a normal distribution with median 1 
        # layer1_weights = np.random.normal(size = final.shape[1]) 
        return np.transpose(np.matrix(weights))

    # Tokenize funtion breaks the string into smalled word bits which can be used for the following steps to better understand the string
    def tokenize(self, s):
        #Lowercase every string
        s = s.lower()
        #convert emojis to text
        s = emoji.demojize(s, delimiters=("", ""))
        s = emoji.demojize(s, delimiters=("", ""))
        answ = emot.emoticons(s)
        if(str(type(answ))== "<class 'list'>"):
            answ = answ[0]
        if(answ['flag']):
            # s = s.replace(answ['value'],answ['mean'])
            j = 0
            for i in answ['value']:
                s = s.replace(i, " "+ answ['mean'][j].split()[-1])
                j = j+1
        # s = s.replace(ans['value'],ans['mean'])
        # Remove punctuation and all weird characters
        s = re.sub("\W"," ", s)
        # Special character cleaning
        s = re.sub("\s"," ", s)
        return list(s.split())

    def sigmoid(self,x):
        return 1/(1+np.exp(-1*x))

    def sigmoid_vec(self,x):
        return np.vectorize(self.sigmoid)(x)

    def log_likelihood( self):
        x = np.sum(np.multiply(self.y_train , (self.X * self.weights))) - np.sum(np.log(1+ np.exp((self.X * self.weights ))))
        self.training_data_log_likehood.append(x)
        return x 

    def zero_or_one(self,x):
        if(x>(0.50)):
            return 1 
        return 0

    def zero_or_one_vec(self,x):
        return np.vectorize(self.zero_or_one)(x)

    def gradient_cal(self):
        y_result = self.y_train - self.zero_or_one_vec(self.sigmoid_vec(self.X * self.weights  ))
        return np.transpose(self.X)*y_result
    
    def stochastic_gradient_cal(self, n ):
        y_result = self.y_train[n] - self.zero_or_one_vec(self.sigmoid_vec(self.X[n] * self.weights  ))
        return np.transpose(self.X[n])*y_result

    # This function reads through the training data and populates a weight matrix shich storing the dictonary with weights in the self.X_dict variable 
    def document_count(self):
        count_in_doc = {}
        for x in self.x_train:
            for i in self.tokenize(x):
                if i not in count_in_doc:
                    count_in_doc[i] = [0]*12000
        count_in_doc["BIAS"]= [1]*12000
        for k in range(len(x_train)):
            i_long = self.tokenize(self.x_train[k])
            for i in i_long:
                count_in_doc[i][k] = (i_long.count(i))
        l = []
        for key, value in count_in_doc.items():
            l.append(count_in_doc[key])
        l = np.transpose(np.matrix(l))
        # print(l.shape)
        self.X_dict = count_in_doc
        return l
    
    def logistic_regression(self, learning_rate = 5*(10**(-5)) ,steps  =  100000):
        for i in range(steps):
            random_number = random.randint(0,self.X.shape[0]-1)
            n =self.stochastic_gradient_cal(random_number)
            self.weights = self.weights + learning_rate* n
            if(i%1000 == 0):
                print(i, self.log_likelihood())

    def predict(self, x_test):
        temp_count_in_doc = {}
        size = len(x_test)
        for key, value in self.X_dict.items():
            temp_count_in_doc[key] = [0]* size
        temp_count_in_doc["BIAS"] = [1]* size
        for k in range(len(x_test)):
            i_long = self.tokenize(x_test[k])
            for i in i_long:
                if(i in temp_count_in_doc):
                    temp_count_in_doc[i][k] = (i_long.count(i))
        # print(temp_count_in_doc)
        l = []
        for key, value in temp_count_in_doc.items():
            l.append(temp_count_in_doc[key])
        l = np.transpose(np.matrix(l))
        # print(l.shape, self.weights.shape)
        return self.zero_or_one_vec(self.sigmoid_vec(l  * self.weights  ))

    def predict_write_to_file(self,x_test):
        result = result = np.transpose(self.predict(x_test)).tolist()[0]
        f = open('numbers_lr_v1.csv', 'w')
        with f:
            writer = csv.writer(f)
            writer.writerow(["Id", "Category"])
            n= 0 
            for row in result:
                writer.writerow([n ,row])
                n = n+1

    def f_score_one(self, x_dev, y_dev):
        result = self.predict(x_dev)
        n = (f1_score(y_dev, result, average = 'weighted'))
        print(n)


In [200]:
x_train = open('X_train.txt').readlines()
y_train = open('Y_train.txt').readlines()
y_train = [ 0 if x == "0\n" else 1 for x in y_train] 
x_test = open('X_test.txt').readlines()
x_dev= open('X_dev.txt').readlines()
y_dev = open('y_dev.txt').readlines()
y_dev = [ 0 if x == "0\n" else 1 for x in y_dev] 
lr = LR_v1(x_train,x_test, y_train)
lr.logistic_regression()


0 -8317.966187765905
1000 -8317.319471470866
2000 -8316.99878306368
3000 -8316.607664844605
4000 -8316.293802555245
5000 -8316.540682870525
6000 -8316.674289244023
7000 -8316.118370984954
8000 -8316.08433187938
9000 -8315.749602843673
10000 -8316.030944251748
11000 -8315.902816118518
12000 -8316.127968908835
13000 -8315.914736683868
14000 -8315.846283612478
15000 -8315.90122123869
16000 -8315.939491984647
17000 -8316.151742024664
18000 -8315.479358315573
19000 -8315.82152046213
20000 -8315.904177838156
21000 -8315.948490665054
22000 -8315.51019069707
23000 -8315.749745280347
24000 -8315.570067787623
25000 -8315.683900139244
26000 -8315.24784579086
27000 -8315.50152410823
28000 -8315.257334300079
29000 -8315.600770780931
30000 -8315.416610507102
31000 -8315.161323082175
32000 -8315.186967625259
33000 -8315.224830835203
34000 -8315.40883638832
35000 -8315.677312574455
36000 -8315.126453230618
37000 -8314.964689777384
38000 -8315.36659947561
39000 -8315.490492480892
40000 -8315.2031611508

In [201]:
lr.predict_write_to_file(x_test)

In [202]:
lr.f_score_one( x_dev, y_dev)

0.78000594903676
